# Generated by Django 4.2.1 on 2023-12-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwt_gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='slug',
        ),
        migrations.AddField(
            model_name='gallery',
            name='caption',
            field=models.CharField(default='Please write your caption here...', max_length=300),
        ),
    ]
