# Generated by Django 4.2.7 on 2023-11-28 19:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=300, unique=True)),
                ('confirmed_day', models.DateField(blank=True, null=True)),
                ('confirmed_time', models.TimeField(blank=True, null=True)),
                ('preferred_day', models.CharField(choices=[('Wednesday', 'wednesday'), ('Thursday', 'thursday'), ('Friday', 'friday'), ('Saturday', 'saturday')], default='Wednesday')),
                ('preferred_time', models.CharField(choices=[('Morning', 'morning'), ('Afternoon', 'afternoon')], default='Morning')),
                ('cover_up', models.CharField(choices=[('Yes', 'yes'), ('No', 'No')], default='No')),
                ('color_or', models.CharField(choices=[('Colour', 'colour'), ('Black and Grey', 'black and grey')], default='Colour')),
                ('tattoo_location', models.CharField(default='Upper left arm', max_length=75)),
                ('tattoo_description', models.TextField()),
                ('reference_images', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('terms', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
