# Generated by Django 4.2.1 on 2023-11-28 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kwt_appointment', '0002_alter_booking_reference_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email_address',
            field=models.ForeignKey(max_length=300, on_delete=django.db.models.deletion.CASCADE, related_name='client_email', to=settings.AUTH_USER_MODEL),
        ),
    ]
