# Generated by Django 4.2.1 on 2023-11-30 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kwt_appointment', '0004_alter_booking_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email_address',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='client_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
