# Generated by Django 4.2.1 on 2023-12-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwt_appointment', '0005_alter_booking_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='color_or',
            field=models.CharField(choices=[('Colour', 'colour'), ('Black and Grey', 'black and grey')]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cover_up',
            field=models.CharField(choices=[('Yes', 'yes'), ('No', 'No')]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferred_day',
            field=models.CharField(choices=[('Wednesday', 'wednesday'), ('Thursday', 'thursday'), ('Friday', 'friday'), ('Saturday', 'saturday')]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferred_time',
            field=models.CharField(choices=[('Morning', 'morning'), ('Afternoon', 'afternoon')]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tattoo_location',
            field=models.CharField(max_length=75),
        ),
    ]
