# Generated by Django 4.2.1 on 2023-12-01 14:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwt_appointment', '0007_alter_booking_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reference_images',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
