# Generated by Django 4.2.1 on 2023-12-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwt_appointment', '0008_alter_booking_reference_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='color_or',
            field=models.CharField(choices=[('colour', 'Colour'), ('black and grey', 'Black and Grey')]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cover_up',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferred_day',
            field=models.CharField(choices=[('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferred_time',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')]),
        ),
    ]
